name: Build and deploy Node.js app to Azure Web App - selfregulator-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Change directory to backend app before installing
      - name: npm install for backend
        working-directory: ./apps/backend  # Specify the backend directory
        run: |
          npm install  # This will now install only the backend dependencies

      # Build the backend app
      - name: Build the backend app
        working-directory: ./apps/backend
        run: |
          npm run build:be --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: ./apps/backend  # TODO Only upload the backend app files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend-app  # TODO Download only the backend app artifact

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'selfregulator-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E07222E134E748739AB5EE40BD35DC41 }}
          package: ./apps/backend  # TODO Deploy only the backend app
